= Сайт-блог с постами и комментами

== ПРАВИЛА

. не противоречить спецификации
. не добавлять новое, что не указано в спецификации
- следствие из этого правила - если какое то поведение не описано, то делать максимально похоже на дефолтное с точки зрения нативности. Забыли описать какой то кейс в спецификации - значит в этом кейсе должно происходить что-то, максимально близкое к "ничего не происходит", чтобы можно было аргументировать, что мы не забыли, а намеренно не описывали, потому что не видели смысла в пункте спецификации "в таком то кейсе ничего не происходит"

== Возможные фичи

- Лайки для коммента
- Изменение коммента
- Удаление коммента
- Удаление нотификейшена
- Различение тега из коммента или из поста
- Добавление к нотификейшену куска текста с тегом, чтобы вместо "вас отметили, перейти" отображался конкретный текст-причина нотификейшена
- Числовая статистика в своем профиле: сколько я поставил лайков, сколько мне поставили лайков, сколько я оставил комментов, сколько мне оставили комментов, сколько я постов запостил. За все время, за период из списка предопределенных периодов, за кастомный период
- Графическая статистика - то же самое, что числовая, но графиками по времени
- Список своих подписчиков
- Рич текст едитор для тела поста и коммента - сам маслаков предлагал когда писали фс
- Поиск по постам на странице своего и чужого профиля
- Поиск по комментам на странице поста
- Закрепление поста на странице своего профиля
- Реплаи для комментов
- Дизлайки к постам
- Дизлайки к комментам
- Почта к юзеру, уведомления на почту от разных действий, верификация по почте
- Аватарки юзеру
- Картинки к постам
- Любые файлы к постам
- Картинки к комментам
- Любые файлы к комментам
- Удаление юзером самого себя
- Рекомендации постов - например, посты всех юзеров, на которых подписаны те, на кого подписан ты, или посты всех юзеров, на которых подписаны твои подписчики
- Разделение юзеров по ролям - юзер и админ, добавление админу удалять любые посты и комменты, банить юзеров, етс
- Сообщения между юзерами, личные чаты
- Группы юзеров - добавление постов от группы в фид всех подписчиков группы, как паблик в вк или канал в тг
- Отображение даты и времены создания нотификейшена
