version: "3.7"

services:
  postgres:
    container_name: "postgres"
    image: "postgres:latest"
    restart: "always"
    environment:
      POSTGRES_DB: "main"
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "postgres"
    ports:
      - "5432:5432"

  back:
    container_name: "back"
    build:
      dockerfile: "Dockerfile"
    environment:
      DB_URL: "jdbc:postgresql://postgres:5432/main"
    ports:
      - "8080:8080"
    depends_on:
      - "postgres"
