const FIELD_MIN_LENGTH = 8;
const FIELD_MAX_LENGTH = 50;
const FIELD_REGEX = /^[A-Za-z0-9]+$/i;

const SHORT_INFO_MIN_LENGTH = 1;
const SHORT_INFO_MAX_LENGTH = 250;

export {
  FIELD_MAX_LENGTH,
  FIELD_MIN_LENGTH,
  FIELD_REGEX,
  SHORT_INFO_MAX_LENGTH,
  SHORT_INFO_MIN_LENGTH,
};
